server:
  port: 9090
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers

job-offers:
  offer-response:
    http:
      client:
        config:
          connectionTimeout: 5000
          readTimeout: 5000
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com:5057/offers




